### ISSUE TITLE
StereoPanner strange behavior

### ISSUE THREAD

**Issue by AdrienFromToulouse** [mohayonao/web-audio-engine#37]
Hi @mohayonao -san !

I was trying to use the StereoPanner. But it sounds like it has some trouble to handle AudioBuffer from a stereo file...I get silence. I hope you could have a look and tell me if you do think it could comes from the implementation of the StereoPanner or if I did a crappy mistake in my script :/

Indeed it works well with an oscillator but from an audioSource I have to force `panNode.channelCount` to `1` to make it works, otherwise I get silence. But then, it looks like both channels are completely mixed together => if  `panNode.pan.value = 0` left and right channel contains mix of both, i.e mono like.

Here is the Gist ready to be run with wae by changing the path of the audio file: 
https://gist.github.com/AdrienFromToulouse/46740802f6acd50430404de66b0b9d46

`wae stereoPanner-test.js`

Audio file on S3 in Japan :) (to be downloaded):

https://s3-ap-northeast-1.amazonaws.com/stereo-panner-test/MixTwoDifferentChannels.wav

I would be very thankful if you could give me your opinion on this.

Cheers!

**Comment by buramensky** [comment]
Same issue :( 
I've noticed that StereoPanner works fine with mono input but in case of stereo it produces just silence.

**Comment by buramensky** [comment]
@mohayonao Thanks! You're awesome! :+1:

**Comment by mohayonao** [comment]
I fixed this problem at v0.9.3. thanks for your reports!
