### ISSUE TITLE
AudioNode.connect(AudioParam) doesn't work for biquad filter and delay node

### ISSUE THREAD

**Issue by buramensky** [mohayonao/web-audio-engine#43]
Hi @mohayonao!
Thanks for your amazing audio engine, it's great thing!

I noticed that control of some parameters by audio signal doesn't work. Specifically, I tested frequency of biquad filter, delay time of delay node and gain of gain node on [benchmark page](http://mohayonao.github.io/web-audio-engine/benchmark/). Only gain node works properly :(

In example below `wae` doesn't change filter's frequency and output signal, but Web Audio API does.

```
module.exports = function(context) {
 var osc = context.createOscillator(),
   lfoOsc = context.createOscillator(),
   lfoScaler = context.createGain(),
   filter = context.createBiquadFilter();

 filter.type = 'allpass';

 lfoOsc.frequency.value = 5;
 lfoScaler.gain.value = 80;
 lfoOsc.connect(lfoScaler);
 lfoScaler.connect(filter.frequency);

 osc.frequency.value = 100;
 filter.frequency.value = 100;
 osc.connect(filter);
 filter.connect(context.destination);

 osc.start();
 lfoOsc.start();
};
```

**Comment by mohayonao** [comment]
oops!! Thank you for your report.
I will fix it at this week end.

**Comment by buramensky** [comment]
Cool! Thanks @mohayonao! I'm looking forward to the fix! :)

**Comment by mohayonao** [comment]
I've fixed this issue.
You can check fixed version at demo page.

- https://mohayonao.github.io/web-audio-engine/demo/#test_filter-modulation
- https://mohayonao.github.io/web-audio-engine/demo/#test_delay-modulation

But, I did not change delay node. I seem to work fine.
Would you tell me a test code that replicate bug?
